// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResumeAPI.Data;

#nullable disable

namespace ResumeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324122658_AddIsCoreWeighting")]
    partial class AddIsCoreWeighting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResumeAPI.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "TechCorp",
                            Description = "Build scalable Python APIs.",
                            Title = "Python Backend Developer"
                        },
                        new
                        {
                            Id = 2,
                            Company = "WebSolutions",
                            Description = "Frontend + backend web development.",
                            Title = "Full Stack Developer"
                        },
                        new
                        {
                            Id = 3,
                            Company = "DataLabs",
                            Description = "ML model building and data analysis.",
                            Title = "Data Scientist"
                        },
                        new
                        {
                            Id = 4,
                            Company = "CloudOps",
                            Description = "CI/CD, infrastructure, and cloud.",
                            Title = "DevOps Engineer"
                        },
                        new
                        {
                            Id = 5,
                            Company = "EnterpriseSoft",
                            Description = "Enterprise application development with .NET.",
                            Title = ".NET Developer"
                        },
                        new
                        {
                            Id = 6,
                            Company = "UIStudio",
                            Description = "Build modern React UIs.",
                            Title = "Frontend React Developer"
                        },
                        new
                        {
                            Id = 7,
                            Company = "DBMasters",
                            Description = "Manage and optimize databases.",
                            Title = "Database Administrator"
                        },
                        new
                        {
                            Id = 8,
                            Company = "AI Dynamics",
                            Description = "Deploy and tune ML models.",
                            Title = "Machine Learning Engineer"
                        },
                        new
                        {
                            Id = 9,
                            Company = "SkyArch",
                            Description = "Design cloud-native architectures.",
                            Title = "Cloud Solutions Architect"
                        },
                        new
                        {
                            Id = 10,
                            Company = "MicroTech",
                            Description = "Build Java-based microservices.",
                            Title = "Java Microservices Developer"
                        });
                });

            modelBuilder.Entity("ResumeAPI.Models.JobSkill", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCore")
                        .HasColumnType("boolean");

                    b.HasKey("JobId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSkills");

                    b.HasData(
                        new
                        {
                            JobId = 1,
                            SkillId = 1,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 1,
                            SkillId = 6,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 1,
                            SkillId = 7,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 1,
                            SkillId = 23,
                            IsCore = false
                        },
                        new
                        {
                            JobId = 1,
                            SkillId = 22,
                            IsCore = false
                        },
                        new
                        {
                            JobId = 1,
                            SkillId = 20,
                            IsCore = false
                        },
                        new
                        {
                            JobId = 2,
                            SkillId = 4,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 2,
                            SkillId = 5,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 2,
                            SkillId = 10,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 2,
                            SkillId = 13,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 2,
                            SkillId = 6,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 2,
                            SkillId = 22,
                            IsCore = false
                        },
                        new
                        {
                            JobId = 2,
                            SkillId = 23,
                            IsCore = false
                        },
                        new
                        {
                            JobId = 3,
                            SkillId = 1,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 3,
                            SkillId = 16,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 3,
                            SkillId = 17,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 3,
                            SkillId = 28,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 3,
                            SkillId = 29,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 3,
                            SkillId = 30,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 3,
                            SkillId = 6,
                            IsCore = false
                        },
                        new
                        {
                            JobId = 4,
                            SkillId = 20,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 4,
                            SkillId = 21,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 4,
                            SkillId = 25,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 4,
                            SkillId = 27,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 4,
                            SkillId = 22,
                            IsCore = false
                        },
                        new
                        {
                            JobId = 5,
                            SkillId = 3,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 5,
                            SkillId = 14,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 5,
                            SkillId = 15,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 5,
                            SkillId = 6,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 5,
                            SkillId = 7,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 5,
                            SkillId = 23,
                            IsCore = false
                        },
                        new
                        {
                            JobId = 5,
                            SkillId = 22,
                            IsCore = false
                        },
                        new
                        {
                            JobId = 6,
                            SkillId = 4,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 6,
                            SkillId = 5,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 6,
                            SkillId = 10,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 6,
                            SkillId = 22,
                            IsCore = false
                        },
                        new
                        {
                            JobId = 7,
                            SkillId = 6,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 7,
                            SkillId = 7,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 7,
                            SkillId = 8,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 7,
                            SkillId = 9,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 8,
                            SkillId = 1,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 8,
                            SkillId = 16,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 8,
                            SkillId = 18,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 8,
                            SkillId = 19,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 8,
                            SkillId = 20,
                            IsCore = false
                        },
                        new
                        {
                            JobId = 8,
                            SkillId = 22,
                            IsCore = false
                        },
                        new
                        {
                            JobId = 9,
                            SkillId = 25,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 9,
                            SkillId = 26,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 9,
                            SkillId = 21,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 9,
                            SkillId = 20,
                            IsCore = false
                        },
                        new
                        {
                            JobId = 9,
                            SkillId = 27,
                            IsCore = false
                        },
                        new
                        {
                            JobId = 10,
                            SkillId = 2,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 10,
                            SkillId = 6,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 10,
                            SkillId = 23,
                            IsCore = true
                        },
                        new
                        {
                            JobId = 10,
                            SkillId = 20,
                            IsCore = false
                        },
                        new
                        {
                            JobId = 10,
                            SkillId = 24,
                            IsCore = false
                        },
                        new
                        {
                            JobId = 10,
                            SkillId = 22,
                            IsCore = false
                        });
                });

            modelBuilder.Entity("ResumeAPI.Models.Resume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("ResumeAPI.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 3,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 4,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 5,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 6,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 7,
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = 8,
                            Name = "MySQL"
                        },
                        new
                        {
                            Id = 9,
                            Name = "MongoDB"
                        },
                        new
                        {
                            Id = 10,
                            Name = "React"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Vue"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = 14,
                            Name = ".NET"
                        },
                        new
                        {
                            Id = 15,
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Deep Learning"
                        },
                        new
                        {
                            Id = 18,
                            Name = "TensorFlow"
                        },
                        new
                        {
                            Id = 19,
                            Name = "PyTorch"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Kubernetes"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Git"
                        },
                        new
                        {
                            Id = 23,
                            Name = "REST API"
                        },
                        new
                        {
                            Id = 24,
                            Name = "GraphQL"
                        },
                        new
                        {
                            Id = 25,
                            Name = "AWS"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Azure"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Linux"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Data Analysis"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Pandas"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Scikit-learn"
                        });
                });

            modelBuilder.Entity("ResumeAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ResumeAPI.Models.JobSkill", b =>
                {
                    b.HasOne("ResumeAPI.Models.Job", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResumeAPI.Models.Skill", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ResumeAPI.Models.Resume", b =>
                {
                    b.HasOne("ResumeAPI.Models.User", "User")
                        .WithMany("Resumes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResumeAPI.Models.Job", b =>
                {
                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("ResumeAPI.Models.Skill", b =>
                {
                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("ResumeAPI.Models.User", b =>
                {
                    b.Navigation("Resumes");
                });
#pragma warning restore 612, 618
        }
    }
}
